name: main

on:
  push:
    branches: [main, bevy_main]
  pull_request:
    branches: [main, bevy_main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2

      - run: cargo check --release --no-default-features

      - run: cargo check --release
      - run: cargo test --release

      - run: cargo check --release --all-features
      - run: cargo test --release --all-features

      - run: cargo fmt --all -- --check

      - run: cargo clippy --release -- --deny warnings
        if: matrix.os != 'windows-latest'
      - run: cargo clippy --release --workspace -- --deny warnings
        if: matrix.os == 'windows-latest'

      - run: cargo build --release -p example
        if: matrix.os == 'windows-latest'

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: example-windows
          path: |
            target/release/*.exe
            target/release/*.bin
          if-no-files-found: error
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --all-features --lcov --output-path lcov.info
      - uses: actions/upload-artifact@v3
        with:
          name: lcov.info
          path: lcov.info
          if-no-files-found: error
      - name: Upload to codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -f lcov.info -Z
